name: Example workflow using Snyk

on: push

jobs:
  security:
    runs-on: ubuntu-latest
    environment: outsystems
    steps:
      - uses: actions/checkout@master

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --json-file-output=snyk.json

      - name: install snyk-to-html
        run: |
          npm install snyk-to-html -g
          cat snyk.json | snyk-to-html -o result.html
          mkdir downloads
          pwd
          ls -al
          cp -v "${GITHUB_WORKSPACE}"/*.html downloads/

      - name: Run Snyk test
        uses: actions/upload-artifact@v4
        with:
          name: results
          path: downloads
